name: SuperCore
main: me.mariozgr8.supercore.SuperCore
version: 1.0

commands:
  fly:
    usage: /fly [args]
    description: Toggle Fly Mode
    aliases: [sfly]
  god:
    usage: /god [args]
    description: Toggle God Mode
    aliases: [sgod]
  statistics:
    usage: /statistics [args]
    description: Open stats menu
    aliases: [stats, sstats, sstatistics]
  setspawn:
    usage: /setspawn
    description: Change spawn location
    aliases: [ssetspawn]
  spawn:
    usage: /spawn [args]
    description: Teleport player to spawn
    aliases: [sspawn]
  setwarp:
    usage: /setwarp [args]
    description: Create new warp location
    aliases: [ssetwarp]
  warp:
    usage: /warp [args]
    description: Teleport player to warp
    aliases: [swarp]
  delwarp:
    usage: /delwarp [args]
    description: Delete warps
    aliases: [sdelwarp]
  feed:
    usage: /feed [args]
    description: Feed player
    aliases: [sfeed]
  heal:
    usage: /heal [args]
    description: Heal player
    aliases: [sheal]
  invsee:
    usage: /invsee [args]
    description: Invsee offline/online players
    aliases: [sinvsee]
  sethome:
    usage: /sethome [args]
    description: Create a new player home
    aliases: [ssethome]
  delhome:
    usage: /delhome [args]
    description: Delete a player home
    aliases: [sdelhome]
  homes:
    usage: /homes [args]
    description: List player homes
    aliases: [shomes]
  home:
    usage: /home [args]
    description: Teleport to player home
    aliases: [shome]

permissions:
  supercore.fly:
    default: OP
    description: Allow /fly
  supercore.fly.others:
    default: OP
    description: Allow /fly [name]
  supercore.god:
    default: OP
    description: Allow /god
  supercore.god.others:
    default: OP
    description: Allow /god [name]
  supercore.statistics:
    default: OP
    description: Allow /stats
  supercore.statistics.others:
    default: OP
    description: Allow /stats [name]
  supercore.setspawn:
    default: OP
    description: Allow /setspawn 
  supercore.spawn:
    default: OP
    description: Allow /spawn
  supercore.spawn.others:
    default: OP
    description: Allow /spawn [args]
  supercore.setwarp:
    default: OP
    description: Allow /setwarp [args]
  supercore.warp:
    default: OP
    description: Allow /warp [args]
  suprecore.delwarp:
    default: OP
    description: Allow /delwarp [args]
  supercore.feed:
    default: OP
    description: Allow /feed
  supercore.feed.others:
    default: OP
    description: Allow /feed [args]
  supercore.heal:
    default: OP
    description: Allow /heal
  supercore.heal.others:
    default: OP
    description: Allow /heal [args]
  supercore.invsee:
    default: OP
    description: Allow players to use /invsee 
  supercore.invsee.modify:
    default: OP
    description: Allow players to modify players inventory while in /invsee
  supercore.invsee.offline:
    default: OP
    description: Allow playerrs to access/modify players invetnroy while they are offline
  supercore.sethome:
    default: OP
    description: Allow player to create homes
  supercore.delhome:
    default: OP
    description: Allow player to delete homes
  supercore.homes:
    default: OP
    description: Allow player to list their homes
  supercore.homes.others:
    default: OP
    description: Allow player to list other player's homes
  supercore.home:
    default: OP
    description: Allow players to teleport to their home
  supercore.home.others:
    default: OP
    description: Allow players to teleport to others homes
